name: renewed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  timezone: ^0.10.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/Renewed.png
    - shorebird.yaml

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Renewed.png"

